### ISSUE TITLE
您好，最近使用了您的库，但是在做编译优化的时候发现AxcAE_TabBar.h AxcAE_TabBar.m 编译时间过长，主要原因是警告太多，我的用的是xcode 10

### ISSUE THREAD

**Issue by yangzheng006** [axclogo/AxcAE_TabBar#16]
<img width="790" alt="wx20181010-154121 2x" src="https://user-images.githubusercontent.com/10958391/46720721-ea73e700-cca3-11e8-9129-14c3befc864b.png">

**Comment by axclogo** [comment]
XCode 10估计有淘汰一批API和新增了代码规范，等我升级好后就更新，我目前是XCode9，没警告

**Comment by yangzheng006** [comment]
我又新建了一个工程看了一下，貌似没有警告，您到时候再看一下吧，应该是我这边的问题
